resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/13.yaml

packages:
- .

extra-deps:
- emoji-0.1.0.2
- discord-haskell-1.8.8

allow-different-user: true
