resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/17.yaml

packages:
- bridge-diagrams-cli
- bridge-diagrams-core
- bridge-diagrams-discord
- bridge-diagrams-slack

extra-deps:
- discord-haskell-1.9.2
- emoji-0.1.0.2

allow-different-user: true
