_package-common: !include "../package-common.yaml"

name:                bridge-diagrams-discord
version:             0.1.0.0
<<: *common-legal

description:         Bridge Hand Diagrams Discord Bot

defaults:
  local: ../package-defaults.yaml

dependencies:
- base >= 4.7 && < 5
- bridge-diagrams-core
- discord-haskell
- either
- text

library:
  source-dirs: src

executables:
  bridge-discord-exe:
    <<: *common-exe
    dependencies:
    - bridge-diagrams-discord
    when:
    - condition: false
      other-modules: Paths_bridge_diagrams_discord
