name:                bridge-diagrams-core
version:             0.1.0.0
license:             MIT
author:              "Drew Olson"
maintainer:          "drew@drewolson.org"
copyright:           "2021 Drew Olson"

description:         Bridge Hand Diagrams

defaults:
  local: ../package-defaults.yaml

dependencies:
- base >= 4.7 && < 5
- doclayout
- megaparsec
- parser-combinators
- raw-strings-qq
- text

library:
  source-dirs: src

tests:
  bridge-diagrams-core-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bridge-diagrams-core
    - QuickCheck
    - hspec
    - hspec-discover
