_package-common: !include "../package-common.yaml"

name:                bridge-diagrams-core
version:             0.1.0.0
<<: *common-legal

description:         Bridge Hand Diagrams

defaults:
  local: ../package-defaults.yaml

dependencies:
- base >= 4.7 && < 5
- doclayout
- megaparsec
- parser-combinators
- raw-strings-qq
- text

library:
  source-dirs: src

tests:
  bridge-diagrams-core-test:
    <<: *common-test
    dependencies:
    - bridge-diagrams-core
    - QuickCheck
    - hspec
    - hspec-discover
