name:                bridge-diagrams-core
version:             0.1.0.0
license:             MIT
author:              "Drew Olson"
maintainer:          "drew@drewolson.org"
copyright:           "2021 Drew Olson"

description:         Bridge Hand Diagrams

ghc-options:
- -Werror
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- BlockArguments
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- InstanceSigs
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- NoMonomorphismRestriction
- OverloadedStrings
- PatternSynonyms
- QuasiQuotes
- ScopedTypeVariables
- TypeApplications
- TypeFamilies
- TypeOperators
- ViewPatterns

dependencies:
- base >= 4.7 && < 5
- doclayout
- megaparsec
- parser-combinators
- raw-strings-qq
- text

library:
  source-dirs: src

tests:
  bridge-diagrams-core-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bridge-diagrams-core
    - QuickCheck
    - hspec
    - hspec-discover
