_package-common: !include "../package-common.yaml"

name:                bridge-diagrams-slack
version:             0.1.0.0
<<: *common-legal

description:         Bridge Hand Diagrams Slack Bot

defaults:
  local: ../package-defaults.yaml

dependencies:
- base >= 4.7 && < 5
- bridge-diagrams-core
- aeson
- bytestring
- casing
- http-conduit
- network
- text
- transformers
- websockets
- wuss

library:
  source-dirs: src

executables:
  bridge-slack-exe:
    <<: *common-exe
    dependencies:
    - bridge-diagrams-slack
    when:
    - condition: false
      other-modules: Paths_bridge_diagrams_slack
