_package-common: !include "../package-common.yaml"

name:                bridge-diagrams-cli
version:             0.1.0.0
<<: *common-legal

description:         Bridge Hand Diagrams CLI

defaults:
  local: ../package-defaults.yaml

dependencies:
- base >= 4.7 && < 5
- bridge-diagrams-core
- text

library:
  source-dirs: src

executables:
  bridge-cli-exe:
    <<: *common-exe
    dependencies:
    - bridge-diagrams-cli
    when:
    - condition: false
      other-modules: Paths_bridge_diagrams_cli
