name: build

on:
  - push
  - pull_request

jobs:
  check-formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mrkkrp/ormolu-action@v5

  build:
    needs: check-formatting
    name: Build, Test & Upload
    runs-on: ubuntu-latest
    container:
      image: haskell:8.10.7-buster
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}
      - name: Permissions bug workaround
        run: "chown -R $(id -un):$(id -gn) ~"
      - run: stack test --ghc-options=-O2
      - run: cp $(stack exec which bridge-cli-exe) .
      - run: cp $(stack exec which bridge-slack-exe) .
      - run: cp $(stack exec which bridge-discord-exe) .
      - uses: actions/upload-artifact@v2
        with:
          path: ./bridge-*-exe
        if: ${{ github.ref == 'refs/heads/main' }}
